# "org" ensures this Service is used with the correct Serverless Framework Access Key.
# change it to your corresponding org
org: compasspbaws
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: api-tts
service: api-tts

provider:
  name: aws
  runtime: python3.9

functions:

  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get

  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
          
  generateAudioFromText:
    handler: handler.generate_audio_from_text
    events:
      - httpApi:
          path: /v1/tts
          method: post

